services:
  
  db:
    image: postgres:15
    container_name: crm-db-1
    environment:
      POSTGRES_DB: myprojectdb
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  web:
    build: .
    container_name: django-web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - .:/app

  celery:
    build: .
    container_name: celery-worker
    command: celery -A CRM worker -l info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: ${POSTGRES_DB}
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    networks:
      - app_network

volumes:
  db_data:


networks:
  app_network:
    driver: bridge
