# Generated by Django 5.2.5 on 2025-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0002_taskstatus_remove_dealstage_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preferred_contact_mode',
        ),
        migrations.AddField(
            model_name='dealstage',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='order',
            field=models.PositiveIntegerField(default=1, unique=True),
        ),
    ]
