# Generated by Django 5.2.5 on 2025-09-27 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0003_remove_customer_preferred_contact_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lead',
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crmnew.lead'),
        ),
        migrations.AddField(
            model_name='activity',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crmnew.activity'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmnew.taskstatus'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('whatsapp', 'Whatsapp'), ('meeting', 'Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='value',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
