# Generated by Django 5.2.5 on 2025-09-29 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0004_remove_task_customer_remove_task_deal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealstage',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
        migrations.CreateModel(
            name='LeadStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='crmnew.leadstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='crmnew.leadstatus')),
            ],
            options={
                'unique_together': {('from_status', 'to_status')},
            },
        ),
    ]
