# Generated by Django 5.2.5 on 2025-09-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0005_remove_activity_performed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealStageTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='crmnew.dealstage')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='crmnew.dealstage')),
            ],
            options={
                'unique_together': {('from_status', 'to_status')},
            },
        ),
    ]
