# Generated by Django 5.2.5 on 2025-09-30 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0006_dealstagetransition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealstagetransition',
            old_name='from_status',
            new_name='from_stage',
        ),
        migrations.RenameField(
            model_name='dealstagetransition',
            old_name='to_status',
            new_name='to_stage',
        ),
        migrations.AlterUniqueTogether(
            name='dealstagetransition',
            unique_together={('from_stage', 'to_stage')},
        ),
    ]
