# Generated by Django 5.2.5 on 2025-09-30 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0007_rename_from_status_dealstagetransition_from_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='deal',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='deal',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='deals', to='crmnew.activity'),
        ),
        migrations.AddField(
            model_name='lead',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crmnew.activity'),
        ),
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='crmnew.task'),
        ),
    ]
