# Generated by Django 5.2.6 on 2025-10-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0008_remove_activity_deal_remove_activity_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(default='Untitled Deal', max_length=200),
        ),
    ]
