# Generated by Django 5.2.6 on 2025-10-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0010_activitytype_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Contact', max_length=200),
        ),
    ]
