# Generated by Django 5.2.6 on 2025-10-03 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0011_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='customer',
        ),
        migrations.AlterField(
            model_name='deal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crmnew.lead'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='crmnew.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default='No name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crmnew.organization'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='crmnew.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
