# Generated by Django 5.2.6 on 2025-10-03 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0012_remove_contactinfo_customer_alter_deal_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='crmnew.lead'),
        ),
    ]
