# Generated by Django 5.2.6 on 2025-10-05 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0013_alter_contactinfo_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_infos', to='crmnew.lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='crmnew.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_man', 'Sales Manager'), ('sales_rep', 'Sales Representative'), ('support', 'Support Staff')], default='sales_rep', max_length=20),
        ),
    ]
