# Generated by Django 5.2.6 on 2025-10-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0014_alter_contactinfo_lead_alter_lead_organization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
