# Generated by Django 5.2.5 on 2025-10-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0014_alter_contactinfo_lead_alter_lead_organization_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='lead',
            name='organization',
        ),
        migrations.AddField(
            model_name='lead',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='leads', to='crmnew.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_rep', 'Sales Representative'), ('support', 'Support Staff')], default='sales_rep', max_length=20),
        ),
    ]
