# Generated by Django 5.2.5 on 2025-10-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0015_role_remove_lead_organization_lead_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales_rep', 'Sales Representative'), ('support', 'Support Staff'), ('sales_mang', 'Sales Manager')], default='sales_rep', max_length=20),
        ),
    ]
