# Generated by Django 5.2.5 on 2025-10-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0016_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('sales_rep', 'Sales Representative'), ('support', 'Support Staff'), ('sales_mang', 'Sales Manager')], default=None, max_length=20, null=True),
        ),
    ]
