# Generated by Django 5.2.5 on 2025-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0017_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
