# Generated by Django 5.2.5 on 2025-10-07 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0019_usertype_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
