# Generated by Django 5.2.6 on 2025-10-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0020_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_followup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
