# Generated by Django 5.2.6 on 2025-10-08 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0021_lead_next_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='qualification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
