# Generated by Django 5.2.6 on 2025-10-10 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0022_alter_activity_assigned_to_alter_lead_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crmnew.activity'),
        ),
    ]
