# Generated by Django 5.2.6 on 2025-10-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmnew', '0023_alter_task_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usertype',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='crmnew.permission'),
        ),
    ]
